#!/usr/bin/env python3
"""Codex (gpt-6-astra) research-then-build chain for a redesigned walkthrough. Step 1: deep research with live web
search into a design spec. Step 2: build WALKTHROUGH_v2.html from the current page's content under the same gate.
Everything is written under tools/walkthrough/redesign/; the current page is never touched."""
import json, pathlib, subprocess, time, hashlib
ROOT = pathlib.Path('/Users/chrism/AI-transformation-assignment/brief-builder'); D = ROOT / 'tools/walkthrough/redesign'; D.mkdir(exist_ok=True)
JOURNAL = '/Users/chrism/.claude/projects/-Users-chrism-AI-transformation-assignment-brief-builder/edd3479c-e412-45f7-b67d-b8ca22a65764/subagents/workflows/wf_b52abbc5-e12/journal.jsonl'
CHROME = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
MUSTKEEP = json.load(open(ROOT / 'tools/walkthrough/round8_args.json'))['mustKeep']
def codex(name, prompt, extra=()):
    (D / f'{name}_prompt.md').write_text(prompt, encoding='utf-8'); log = D / f'{name}.log'; out = D / f'{name}_report.md'
    cmd = ['codex', *extra, 'exec', '-m', 'gpt-6-astra', '-s', 'workspace-write', '-C', str(D), '-o', str(out), prompt]  # root options (e.g. --search) go before the subcommand
    t0 = time.time()
    with open(log, 'w') as lf: rc = subprocess.run(cmd, stdin=subprocess.DEVNULL, stdout=lf, stderr=subprocess.STDOUT, timeout=7200).returncode
    print(f'[{name}] rc={rc} in {time.time()-t0:.0f}s', flush=True); return rc
RESEARCH = f"""You are the design lead of a small studio and a research analyst. Task: deep-research, with LIVE WEB SEARCH and citations, how a decision-grade stakeholder walkthrough of an AI pilot should be presented as a single self-contained HTML file, then write a design specification for THIS walkthrough. Read first (read-only): {ROOT}/WALKTHROUGH.html (the current page, all ten sheets, CSS and scripts); {ROOT}/HANDOFF_WALKTHROUGH.md (the rules the page must keep and its history); {ROOT}/tools/walkthrough/codex_review.md and codex_priorities.md (your own earlier reviews); {ROOT}/tools/walkthrough/checks.py (the deterministic gate: list every structural hook it reads); the round-8 audience findings at {JOURNAL} (JSON lines; each line's result holds answer, missing, confusions and fixes from a CMO, a CFO, a creative director and an engineer who read the page); {ROOT}/docs/PRD.md sections 7 to 9.
The critical information that must survive any redesign is this regression list; treat it as the definition of "critical": {json.dumps(MUSTKEEP, ensure_ascii=False)}
Research areas, each with at least two credible sources cited with URL and access date (prefer primary sources: standards bodies, the original authors, top consultancies' and design studios' published guidance, W3C): (1) consulting-grade storyline for decision documents: pyramid principle and answer-first, action titles, one idea per page, SCQA, how evidence is attached; (2) executive and board pre-read conventions: length, what must be on the first page, decision framing with options, owners and conditions, how costs and risks are stated when unknown; (3) presentation and information design standards: typographic scale and measure, grid and whitespace, data-ink and when a table beats prose, colour use, how citations and receipts are displayed without clutter; (4) accessibility for HTML documents: WCAG 2.2 AA contrast, focus visibility, keyboard operation, reduced motion, target size, reflow at 320 px, headings and landmarks; (5) single-file HTML presentation engineering: zero dependencies, system font stacks, print stylesheet, progressive disclosure (details/summary), hash navigation and history, performance of embedded images, offline opening from disk; (6) how AI pilots are presented to non-technical stakeholders: trust, human-in-the-loop, limits and failure modes, what "shadow mode" must mean to a reader, honest uncertainty; (7) creative and brand work presentation: mock-up labelling, spec tables, showing drafts as drafts.
Write two files in the current directory and nothing else anywhere: research.md (findings by area with citations; what the current page already does well; where it departs from the standards, naming the sheet and quoting the passage) and design_spec.md (the specification an implementer follows: information architecture sheet by sheet, what sits on the face of each sheet and what moves to its ledger, with every regression-list item mapped to a sheet; a visual system as tokens (colour keeping the existing rules: paper #F1F2EC, ink #1A1A18, pencil #5A5D55, red #C8102E only where a person decided, brand blue and yellow only inside the sheet-09 artwork; type scale, spacing, grid, breakpoints); interaction and accessibility requirements; print; the exact structural hooks the gate reads that must be preserved; a numbered list of every deviation from the current page with the standard it answers to and the source). Constraints that stand and are not open for research: at most 10 sheets; zero external resources; every clipping verbatim; usage in tokens not dollars; the budget in words; shadow-mode and mock-up labels; the key visual SVG (id kv-art) and the packaging plate; word budgets (650 visible words per sheet, 750 on sheet 09; titles at most 24 words; takeaways at most 20). Keep research.md under 2500 words and design_spec.md under 2500 words. Plain prose, no praise."""
BUILD = f"""You are the design lead of a small studio, implementing your own specification. Read design_spec.md and research.md in the current directory, then {ROOT}/WALKTHROUGH.html in full (the content source: every fact, clipping, number, ledger, the SVG key visual with id kv-art, the packaging plate data URI on sheet 09, and both scripts). Build a NEW single self-contained file in the current directory, WALKTHROUGH_v2.html, that implements the specification while preserving every item of this regression list: {json.dumps(MUSTKEEP, ensure_ascii=False)}
Hard requirements: zero external resources (no link tags, no @import, no url(), system font stacks, images only as data URIs already present in the source); every blockquote and mark.cited byte-identical to the source; the structural hooks tools/walkthrough/checks.py reads (read the file: section.sheet ids ch01 to ch10 with data-n, h1.title.action ids t01 to t10, folio text "NN / 10 · Contents", var CH = [ ... ]; with one t: entry per sheet, ul.takeaways, ol.decisions with a .decisions > li counter and exactly three top-level decisions, details ledgers, div.page lang el and en with at least two h4 each, classes hero, brief, exam, numbers, decisions, limits, takeaways and flow non-empty, the string SHADOW MODE, the mock-up text element and the wordmark inside kv-art with the attribute order the gate expects, at most 650 visible words per sheet and 750 on sheet 09, action titles at most 24 words, takeaways at most 20; the X3 rule: no numeric budget total except text flagged with mark.flag). Run python3 {ROOT}/tools/walkthrough/checks.py --file ./WALKTHROUGH_v2.html after every batch of changes and iterate until it exits 0; do not weaken any rule to pass. Then render every sheet at 1440 and 390 px into ./screens/ with headless Chrome: "{CHROME}" --headless=new --disable-gpu --hide-scrollbars --user-data-dir=./chrome --window-size=1440,2400 --screenshot=./screens/s01-1440.png "file://{D}/WALKTHROUGH_v2.html#1" (and #2 to #10; 390x844 for phones), look at every screenshot, and fix what you see (overlaps, clipping, dead space, contrast). Finally write build_notes.md: what changed versus the current page and which standard in research.md each change answers; the final checks.py output; visible words per sheet; the regression list with the sheet each item now sits on; known limitations. Do not modify any file outside the current directory; do not touch {ROOT}/WALKTHROUGH.html; no git commands that change state."""
rc1 = codex('research', RESEARCH, extra=('--search',))
rc2 = codex('build', BUILD)
status = {'research_rc': rc1, 'build_rc': rc2, 'v2_exists': (D / 'WALKTHROUGH_v2.html').exists()}
if status['v2_exists']:
    r = subprocess.run(['python3', str(ROOT / 'tools/walkthrough/checks.py'), '--file', str(D / 'WALKTHROUGH_v2.html')], capture_output=True, text=True)
    status['checks_exit'] = r.returncode; status['checks'] = r.stdout[-1500:]; status['v2_sha256'] = hashlib.sha256((D / 'WALKTHROUGH_v2.html').read_bytes()).hexdigest()
g = subprocess.run(['git', 'status', '--short'], cwd=ROOT, capture_output=True, text=True); status['git_status'] = g.stdout
(D / 'status.json').write_text(json.dumps(status, indent=1)); print(json.dumps(status, indent=1), flush=True)
