"""Build tools/walkthrough/can_comparison.html: the two Codex can mock-ups side by side, each above the lockup it was
asked to reproduce, with Codex's own notes. Images embedded as JPEG data URIs (no external resources). Reuses the
walkthrough's paper/ink/pencil/red tokens and type stacks so the page reads as part of the same family."""
import base64, io, pathlib, re, html
from PIL import Image
ROOT = pathlib.Path('/Users/chrism/AI-transformation-assignment/brief-builder'); T = ROOT / 'tools/walkthrough'
def data_uri(path, maxdim=1100, q=84):
    im = Image.open(path).convert('RGB'); s = min(1.0, maxdim / max(im.size))
    im = im.resize((round(im.size[0] * s), round(im.size[1] * s)), Image.LANCZOS)
    b = io.BytesIO(); im.save(b, 'JPEG', quality=q, optimize=True, progressive=True)
    return 'data:image/jpeg;base64,' + base64.b64encode(b.getvalue()).decode('ascii'), im.size
page = (ROOT / 'WALKTHROUGH.html').read_text(encoding='utf-8')
root = re.search(r':root \{[^}]*\}', page).group(0)
report = (T / 'codex_cans.md').read_text(encoding='utf-8') if (T / 'codex_cans.md').exists() else ''
def note_for(key):
    # pull the "still imperfect" sentence for image A or B from Codex's report, if it wrote one
    m = re.search(r'(?s)\*\*\[' + key + r' [^\]]*\]\([^)]*\):\*\*(.*?)(?=\n- \*\*\[|\n\n)', report)
    if not m: return ''
    seg = m.group(1); i = seg.lower().find('imperfections:')
    return html.escape((seg[i:] if i >= 0 else seg).strip()) if seg.strip() else ''
cans = [
    ('A', 'kv_can_A_previous_logo.png', 'kv_previous_logo_ref.png', 'Previous logo', 'The walkthrough&rsquo;s key-visual lockup: ring, leaf, five wind lines, wordmark, line.'),
    ('B', 'kv_can_B_bottle_label.png', 'kv_packaging_mockup.png', 'Bottle label', 'The label drawn for the bottle mock-up: ring, leaf, wordmark, line; no wind lines.'),
]
cols = []
for key, can, ref, title, sub in cans:
    if not (T / can).exists(): continue
    cu, cs = data_uri(T / can); ru, rs = data_uri(T / ref, 420, 80)
    note = note_for(key)
    cols.append(f'''
    <section class="col" aria-labelledby="h{key}">
      <h2 id="h{key}"><span class="k">{key}</span>{title}</h2>
      <figure class="can"><img src="{cu}" width="{cs[0]}" height="{cs[1]}" alt="Can mock-up {key}: a standard 330 ml can of Meltemi Fizz sparkling tea carrying the {title.lower()} lockup, on a flat light backdrop, with a corner caption reading mock-up, not for delivery."><figcaption>Can {key} &middot; standard 330&thinsp;ml &middot; generated by gpt-6-astra (Codex built-in image tool) &middot; <b>mock-up, not for delivery</b></figcaption></figure>
      <figure class="ref"><img src="{ru}" width="{rs[0]}" height="{rs[1]}" alt="Reference lockup for can {key}."><figcaption><span class="lbl">Reference given to the model</span>{sub}</figcaption></figure>
      {f'<p class="note"><span class="lbl">Codex&rsquo;s own note</span>{note}</p>' if note else ''}
    </section>''')
doc = f'''<title>Meltemi Fizz Can Mock-ups</title>
<style>
{root}
:root {{ color-scheme: light; }}
@media (prefers-color-scheme: dark) {{ :root:not([data-theme="light"]) {{ --paper: #1C1D1A; --ink: #ECEDE6; --pencil: #A7AAA0; --rule: #3A3C36; --white: #262823; --bar: #22241F; }} }}
:root[data-theme="dark"] {{ --paper: #1C1D1A; --ink: #ECEDE6; --pencil: #A7AAA0; --rule: #3A3C36; --white: #262823; --bar: #22241F; }}
body {{ margin: 0; background: var(--paper); color: var(--ink); font: 400 17px/26px var(--serif); }}
.desk {{ max-width: 1240px; margin: 0 auto; padding: 40px 32px 64px; }}
.kicker {{ display: flex; gap: 20px; flex-wrap: wrap; align-items: baseline; margin: 0 0 6px; font: 700 11px/16px var(--label); letter-spacing: 0.14em; text-transform: uppercase; color: var(--pencil); }}
.kicker .num {{ color: var(--ink); }}
h1 {{ margin: 0 0 8px; font: 400 40px/46px var(--serif); letter-spacing: -0.01em; text-wrap: balance; max-width: 26ch; }}
.narr {{ margin: 0 0 32px; max-width: 64ch; color: var(--ink); }}
.narr .cite {{ font: 400 13px/20px var(--ledger); color: var(--pencil); }}
.cols {{ display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 40px; align-items: start; }}
.col h2 {{ margin: 0 0 14px; font: 400 26px/32px var(--serif); display: flex; gap: 14px; align-items: baseline; }}
.col h2 .k {{ display: inline-block; width: 30px; height: 30px; border: 1.5px solid var(--red); color: var(--red); font: 700 13px/28px var(--label); text-align: center; }}
figure {{ margin: 0; }}
.can {{ background: var(--white); border: 1px solid var(--rule); box-shadow: 0 1px 0 var(--rule), 0 12px 24px -18px rgba(0,0,0,.35); padding: 16px; }}
.can img, .ref img {{ display: block; width: 100%; height: auto; }}
figcaption {{ margin-top: 10px; font: 400 13px/20px var(--ledger); color: var(--pencil); }}
figcaption b {{ color: var(--ink); font-weight: 700; }}
.ref {{ margin-top: 18px; display: grid; grid-template-columns: 120px 1fr; gap: 16px; align-items: start; }}
.ref img {{ border: 1px solid var(--rule); }}
.ref figcaption {{ margin: 0; font: 400 15px/22px var(--serif); color: var(--ink); }}
.lbl {{ display: block; font: 700 11px/16px var(--label); letter-spacing: 0.14em; text-transform: uppercase; color: var(--pencil); margin-bottom: 4px; }}
.note {{ margin: 16px 0 0; font: 400 15px/22px var(--serif); color: var(--pencil); }}
.foot {{ margin: 40px 0 0; padding-top: 16px; border-top: 1px solid var(--rule); font: 400 13px/20px var(--ledger); color: var(--pencil); max-width: 80ch; }}
@media (max-width: 760px) {{ .cols {{ grid-template-columns: 1fr; }} h1 {{ font-size: 30px; line-height: 36px; }} }}
</style>
<div class="desk">
  <p class="kicker"><span class="num">Brief Builder</span><span>Sheet 09 &middot; packaging application</span><span>Shadow mode &middot; synthetic brand</span></p>
  <h1>Two cans, two lockups: which one goes on sheet 09?</h1>
  <p class="narr">Same scene, same standard 330&thinsp;ml can, same brand rules (Aegean Blue, Citrus Yellow, white; no alcohol, beach or party cues; no health claims). Only the artwork on the can differs: A carries the walkthrough&rsquo;s original key-visual lockup, B the label drawn for the bottle. Pick one and it becomes the packaging plate on sheet 09, labelled as a mock-up generated for the walkthrough. <span class="cite">Packaging is an undefined context in the brief [open_questions/deliverables]; the pipeline itself emits text only.</span></p>
  <div class="cols">{''.join(cols)}
  </div>
  <p class="foot">Generated 2026-09-17 with Codex (gpt-6-astra) using its built-in image tool from tools/walkthrough/codex_cans_prompt.md; references rendered from WALKTHROUGH.html (sheet 09 SVG) and tools/walkthrough/kv_packaging_mockup.png. Files: tools/walkthrough/kv_can_A_previous_logo.png &middot; kv_can_B_bottle_label.png. Nothing here is a deliverable.</p>
</div>
'''
out = T / 'can_comparison.html'; out.write_text(doc, encoding='utf-8'); print('wrote', out, len(doc) // 1024, 'KB,', len(cols), 'columns')
